/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProofOfCare__factory } from "./ProofOfCare__factory";
export { SolunaToken__factory } from "./SolunaToken__factory";
